/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.philosophofee.farctool2.windows;

import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

public class FARChooser extends javax.swing.JDialog {

    MainWindow Window;
    public DefaultListModel TableEntries = new DefaultListModel<String>();
    public boolean isSelected = false;
    public File[] selectedFARCs;
    public FARChooser(MainWindow parent, boolean modal) {
        super(parent, modal);
        this.Window = parent;
        this.setTitle("FARC Chooser");
        this.setIconImage(new ImageIcon(getClass().getResource("resources/farctool2_icon.png")).getImage());
        for (int i = 0; i < Window.FARC.length; i++) this.TableEntries.addElement(Window.FARC[i].getName());
        initComponents();
        this.setVisible(true);
    }
    
    public File[] getSelected() {
        return this.selectedFARCs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FARCList = new javax.swing.JList<>();
        SelectFARCs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        FARCList.setModel(this.TableEntries);
        jScrollPane1.setViewportView(FARCList);

        SelectFARCs.setText("Select .FARCs");
        SelectFARCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectFARCsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(SelectFARCs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectFARCs)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectFARCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectFARCsActionPerformed
       int[] selected = FARCList.getSelectedIndices();
       this.selectedFARCs = new File[selected.length];
       for (int i = 0; i < selected.length; i++) this.selectedFARCs[i] = Window.FARC[selected[i]];
       this.isSelected = true;
       this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_SelectFARCsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> FARCList;
    private javax.swing.JButton SelectFARCs;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
